name: 'Base'
properties:
  id: 
    type: string
    primaryKey: true
    allowNull: false
methods:
  find:
    isStaic: true
    description: 'get instance data with filter'
    accepts:
    - arg: filter
      type: object
      required: false
      description: "filter object"
      source: url
    http: 
      path: '/'
      method: get
    return:
      description: 'return Instance Array [Instance]'
      args: '[Instance]'
      type: 'Array'
  created:
    isStaic: true
    accepts:
    - arg: instance
      type: Instance
      required: false
      source: body
    http: 
      path: '/'
      method: POST
    return:
      args: 'Instance'
      type: 'Object'
  findById:
    isStaic: true
    accepts:
    - arg: id
      type: string
      required: false
    http: 
      path: '/:id'
      method: get
    return:
      args: '[Instance]'
      type: 'Array'