env:
  browser: true
  commonjs: true
  es6: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  linebreak-style: 0
  semi: 0
  arrow-parens: 0
  max-len: 
  - 'error'
  - code: 120
  indent:
  - "error"
  - 2
  - flatTernaryExpressions: true
    ArrayExpression: 1
    ObjectExpression: 1
    ImportDeclaration: 1
    MemberExpression: off
    CallExpression:
      arguments: first
    VariableDeclarator:
      let: 2
      const: 3
