port: 3000
db:
  dev: 
    dialect: "sqlite"
    storage: "./db.development.sqlite"
  test:
    dialect: "sqlite"
    storage: ":memory:"
  production:
    database: "${dbName}"
    dialect: "mysql"
    username: "root"
    password: "${yourPass}"
    host: '${yourHost}'
log:
  level: DEBUG
  options:
    appenders: 
      accessFile:
        type: dateFile
        pattern: "-yyyy-MM-dd"
        filename: 'log/access.log'
      errorFile:
        type: dateFile
        pattern: "-yyyy-MM-dd"
        filename: 'log/error.log'
      access:
        type: logLevelFilter
        level: info
        filename: 'log/access.log'
        appender: accessFile
      error:
        type: logLevelFilter
        level: ERROR
        filename: 'log/access.log'
        appender: errorFile
# create by scripts not define
    categories:
      default: 
        appenders:
        - access
        - error
        level: info 